[package]
name = "waytrogen"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2"
gtk = { version = "0.9.5", package = "gtk4", features = ["v4_16"] }
anyhow = "1.0.95"
sqlite = "0.36.1"
xdg = "2.5.2"
stderrlog = "0.6.0"
log = "0.4.22"
image = "0.25.5"
sysinfo = "0.33.1"
async-channel = "2.3.1"
which = "7.0.1"
strum = "0.26.3"
strum_macros = "0.26.4"
regex = "1.11.1"
lazy_static = "1.5.0"
